DarkSoulsII/Areas/DS3/Controllers/PlannerController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Model.DS3;
using DarkSoulsII.Areas.DS3.Helpers;

namespace DarkSoulsII.Areas.DS3.Controllers
{
    public class PlannerController : Controller
    {
        private readonly WeaponsHelper _weaponsHelper = new WeaponsHelper();
        private readonly ArmorHelper _armorHelper = new ArmorHelper();
        private readonly StatsHelper _statsHelper = new StatsHelper();

        // GET: DS3/Planner
        public ActionResult Index()
        {
            ViewBag.Weapons = _weaponsHelper.GetWeapons();
            ViewBag.ReinforcementLevels = _statsHelper.GetReinforcementLevels();
            ViewBag.Helms = _armorHelper.GetArmor(armorTypeId: (int)ArmorType.Types.Helm);
            ViewBag.Chests = _armorHelper.GetArmor(armorTypeId: (int)ArmorType.Types.Chest);
            ViewBag.Gauntlets = _armorHelper.GetArmor(armorTypeId: (int)ArmorType.Types.Gauntlet);
            ViewBag.Leggings = _armorHelper.GetArmor(armorTypeId: (int)ArmorType.Types.Legging);
            ViewBag.StartingClasses = _statsHelper.GetStartingClasses();
            ViewBag.InfusionTypes = _weaponsHelper.GetInfusionTypes();
            ViewBag.Rings = new List<SelectListItem>();
            return View();
        }

        [HttpGet]
        public JsonResult ChangeStartingClass(int startingClassId)
        {
            StartingClass startingClass = _statsHelper.GetStartingClass(startingClassId);
            return Json(startingClass, JsonRequestBehavior.AllowGet);
        }
    }
}

DarkSoulsII/Controllers/ArmorController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DarkSoulsII.ViewModels;
using DarkSoulsII.Helpers;

namespace DarkSoulsII.Controllers
{
    public class ArmorController : Controller
    {
        private readonly ArmorHelper _armorHelper = new ArmorHelper();
        //private readonly StatsHelper _statsHelper = new StatsHelper();

        // GET: DS3/Armor
        public ActionResult Index(string searchValue = "", int armorTypeId = 0, double? maxWeight = null, double? minPoise = null)
        {
            searchValue = (searchValue == null) ? "" : searchValue.Trim();
            
            IEnumerable<ArmorViewModel> armors = _armorHelper.ArmorSearch(searchValue, null, armorTypeId, maxWeight, minPoise);
            ViewData.Model = armors.OrderBy(a => a.Name).ToList();

            ViewBag.ArmorTypes = _armorHelper.GetArmorTypes(armorTypeId);
            ViewBag.ArmorTypeId = armorTypeId;
            ViewBag.SearchValue = searchValue;
            ViewBag.MaxWeight = maxWeight;
            ViewBag.MinPoise = minPoise;

            return View();
        }

        [HttpGet]
        public ActionResult Details(int armorId)
        {
            ArmorViewModel armor = _armorHelper.ArmorSearch(armorId: armorId).Single();
            return View(armor);
        }

        [HttpGet]
        public JsonResult ArmorAutocomplete(string term)
        {
            term = term.ToLower();
            var armor = _armorHelper.GetArmor().Where(w => w.Text.ToLower().Contains(term));
            return Json(armor, JsonRequestBehavior.AllowGet);
        }
    }
}

DarkSoulsII/Controllers/PlannerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using DarkSoulsII.Infrastructure;
using Autofac;
using System.Data.SqlClient;
using Model.DS2;
using DarkSoulsII.ViewModels;
using DarkSoulsII.Helpers;

namespace DarkSoulsII.Controllers
{
    public class PlannerController : Controller
    {
        private readonly WeaponsHelper _weaponsHelper = new WeaponsHelper();
        private readonly ArmorHelper _armorHelper = new ArmorHelper();
        private readonly RingsHelper _ringsHelper = new RingsHelper();

        // GET: Planner
        public ActionResult Index()
        {
            ViewBag.Vit = 9;
            ViewBag.ADP = 10;
            ViewBag.END = 10;
            ViewBag.WeaponTypes = _weaponsHelper.GetWeaponTypes();
            ViewBag.Weapons = _weaponsHelper.GetWeapons();
            ViewBag.Helms = _armorHelper.GetArmor(armorTypeId: (int)DS2ArmorType.Types.Helm);
            ViewBag.Chests = _armorHelper.GetArmor(armorTypeId: (int)DS2ArmorType.Types.Chest);
            ViewBag.Gauntlets = _armorHelper.GetArmor(armorTypeId: (int)DS2ArmorType.Types.Gauntlet);
            ViewBag.Leggings = _armorHelper.GetArmor(armorTypeId: (int)DS2ArmorType.Types.Legging);
            ViewBag.Rings = _ringsHelper.GetRings();
            return View();
        }

        [HttpPost]
        public ActionResult CalculateEquipBurden(int vit,
                                                 int adp,
                                                 int end,
                                                 int? rWeapon1 = null, 
                                                 int? lWeapon1 = null,
                                                 int? helm = null,
                                                 int? chest = null,
                                                 int? gauntlet = null,
                                                 int? legging = null,
                                                 int? ring1 = null,
                                                 int? ring2 = null,
                                                 int? ring3 = null,
                                                 int? ring4 = null)
        {
            double maxEquipLoad = vit > 29 ? (38.5 + (1.5 * 29) + 1 * (vit - 29)) : (38.5 + (1.5 * vit));
            decimal currentEquipLoad = 0;
            double equipPercentage = 0;
            double poise = 0;

            int relevantPoiseStat = Math.Min(adp, end);
            if (relevantPoiseStat > 50) {
                poise = 30 * .3 + 20 * .2 + .1 * (relevantPoiseStat - 50);
            }
            else if (relevantPoiseStat > 30)
            {
                poise = 30 * .3 + .2 * (relevantPoiseStat - 50);
            } else
            {
                poise = relevantPoiseStat * .3;
            }

            List<Ring> rings = new List<Ring>();
            if (ring1 > 0)
                rings.Add(_ringsHelper.GetRing(ring1.Value));
            if (ring2 > 0)
                rings.Add(_ringsHelper.GetRing(ring2.Value));
            if (ring3 > 0)
                rings.Add(_ringsHelper.GetRing(ring3.Value));
            if (ring4 > 0)
                rings.Add(_ringsHelper.GetRing(ring4.Value));

            foreach (Ring ring in rings)
            {
                currentEquipLoad += ring.Weight;

                if (ring.Effects != null)
                {
                    foreach (Effect effect in ring.Effects)
                    {
                        if (effect.Affects == Effect.Modifies.EquipLoad)
                        {
                            maxEquipLoad = (maxEquipLoad * effect.Amount);
                        }
                    }
                }
            }

            if (rWeapon1 != null)
            {
                WeaponViewModel rW1 = _weaponsHelper.WeaponSearch(weaponId: rWeapon1).First();
                currentEquipLoad += rW1.Weight.Value;
            }

            if (lWeapon1 != null)
            {
                WeaponViewModel lW1 = _weaponsHelper.WeaponSearch(weaponId: lWeapon1).First();
                currentEquipLoad += lW1.Weight.Value;
            }

            if (helm != null)
            {
                ArmorViewModel hlm = _armorHelper.ArmorSearch(armorId: helm).First();
                currentEquipLoad += (decimal)hlm.Weight;
                poise += hlm.Poise;
            }

            if (chest != null)
            {
                ArmorViewModel cht = _armorHelper.ArmorSearch(armorId: chest).First();
                currentEquipLoad += (decimal)cht.Weight;
                poise += cht.Poise;
            }

            if (gauntlet != null)
            {
                ArmorViewModel glt = _armorHelper.ArmorSearch(armorId: gauntlet).First();
                currentEquipLoad += (decimal)glt.Weight;
                poise += glt.Poise;
            }

            if (legging != null)
            {
                ArmorViewModel lgg = _armorHelper.ArmorSearch(armorId: legging).First();
                currentEquipLoad += (decimal)lgg.Weight;
                poise += lgg.Poise;
            }

            equipPercentage = (double)currentEquipLoad / maxEquipLoad;
            string equipLoad = String.Format("{0} / {1} ({2:P2})", currentEquipLoad, maxEquipLoad, equipPercentage);

            return Json(new { equipLoad = equipLoad, poise = poise }, JsonRequestBehavior.AllowGet);
        }
    }
}

DarkSoulsII/Controllers/WeaponsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Model.DS2;
using DarkSoulsII.ViewModels;
using DarkSoulsII.Helpers;

namespace DarkSoulsII.Controllers
{
    public class WeaponsController : Controller
    {
        private readonly WeaponsHelper _weaponsHelper = new WeaponsHelper();
        //private readonly StatsHelper _statsHelper = new StatsHelper();

        // GET: DS3/Weapons
        public ActionResult Index(string searchValue = "", int weaponTypeId = 0, int infusionId = 6,
                                  double? weight = null, int? STR = null, int? DEX = null, int? INT = null, int? FTH = null)
        {
            searchValue = (searchValue == null) ? "" : searchValue.Trim();

            //TODO: Include Bleed/Poison
            IEnumerable<WeaponViewModel> weapons = _weaponsHelper.WeaponSearch(searchValue, null, weaponTypeId, infusionId, weight, STR, DEX, INT, FTH);
            ViewData.Model = weapons.OrderBy(w => w.Name).ToList();

            ViewBag.WeaponTypes = _weaponsHelper.GetWeaponTypes(weaponTypeId);
            ViewBag.InfusionTypes = _weaponsHelper.GetInfusionTypes(infusionId);
            ViewBag.WeaponTypeId = weaponTypeId;
            ViewBag.SearchValue = searchValue;
            ViewBag.Weight = weight;
            ViewBag.STR = STR;
            ViewBag.DEX = DEX;
            ViewBag.INT = INT;
            ViewBag.FTH = FTH;

            return View();
        }

        [HttpGet]
        public ActionResult Details(int weaponId)
        {
            //TODO: Include Bleed/Poison
            IEnumerable<WeaponViewModel> weapons = _weaponsHelper.WeaponSearch(weaponId: weaponId);
            WeaponDetailsView model = new WeaponDetailsView();
            model.Normal = weapons.Single(w => w.Infusion == "Normal");
            model.Infusions = weapons.Where(w => w.Infusion != "Normal").OrderBy(w => w.Infusion).ToList();

            return View(model);
        }

        [HttpGet]
        public ActionResult ARCalculator(int? weaponId = null, int weaponTypeId = 0, int infusionId = 6)
        {
            ViewBag.WeaponTypes = _weaponsHelper.GetWeaponTypes(weaponTypeId);
            ViewBag.Weapons = _weaponsHelper.GetWeapons(weaponId, weaponTypeId);
            ViewBag.InfusionTypes = _weaponsHelper.GetInfusionTypes(infusionId);
            //ViewBag.StartingClasses = _statsHelper.GetStartingClasses();
            return View();
        }

        //[HttpGet]
        //public JsonResult ChangeStartingClass(int startingClassId)
        //{
        //    StartingClass startingClass = _statsHelper.GetStartingClass(startingClassId);
        //    return Json(startingClass, JsonRequestBehavior.AllowGet);
        //}

        [HttpPost]
        public ActionResult CalculateAR(int weaponId, int infusionId, int STR, int DEX, int INT, int FTH)
        {
            //TODO: Include Bleed/Poison
            //if (twoHand)
            //{
            //    STR = (int)System.Math.Floor((double)STR * 1.5);
            //}
            WeaponARModel model = _weaponsHelper.CalculateAR(weaponId, infusionId, STR, DEX, INT, FTH);
            return PartialView("_ARValues", model);
        }

        [HttpGet]
        public JsonResult WeaponsAutocomplete(string term)
        {
            term = term.ToLower();
            var weapons = _weaponsHelper.GetWeapons().Where(w => w.Text.ToLower().Contains(term));
            return Json(weapons, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Weapons(int weaponTypeId = 0)
        {
            var weapons = _weaponsHelper.GetWeapons(weaponCategoryId: weaponTypeId);
            return Json(weapons, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Infusions(int? weaponId = null)
        {
            var infusions = _weaponsHelper.GetInfusionTypes(weaponId: weaponId);
            return Json(infusions, JsonRequestBehavior.AllowGet);
        }
    }
}

DarkSoulsII/Areas/DS3/Views/Planner/Index.cshtml
@using DarkSoulsII.Areas.DS3.ViewModels;

@*@model WeaponViewModel*@
@{
    ViewBag.Title = "Planner";
}

<script type="text/javascript">
    $(document).ready(function () {
        startingClassChanged();
    });

    function startingClassChanged() {
        $.ajax({
            url: 'Planner/ChangeStartingClass',
            type: 'GET',
            data: { startingClassId: $('#startingClassId').val() },
            success: function (response) {
                $('#vgr').val(response.Vigor);
                $('#att').val(response.Attunement);
                $('#end').val(response.Endurance);
                $('#vit').val(response.Vitality);
                $('#str').val(response.Strength);
                $('#dex').val(response.Dexterity);
                $('#int').val(response.Intelligence);
                $('#fth').val(response.Faith);
                $('#lck').val(response.Luck);
            },
            complete: function () {

            }
        });
    }
</script>

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="~/Home">Dark Souls III</a></li>
    <li class="breadcrumb-item active">Character Planner</li>
</ol>

<h4>Character Planner</h4>

<div class="form-group row">
    <label class="col-sm-3">Starting Class:</label>
    <div class="col-sm-5">@Html.DropDownList("startingClassId", ViewBag.StartingClasses as IEnumerable<SelectListItem>, new { onchange = "startingClassChanged();" })</div>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">Attributes</div>
            <div class="panel-body">
                <div class="col-sm-6">
                    <div class="form-group row">
                        <div class="col-sm-6">Vigor</div><div class="col-sm-5">@Html.TextBox("vgr", ViewBag.Vigor as int?, new { type = "number", min = "0", style = "width:50px;" })</div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">Attunement</div><div class="col-sm-5">@Html.TextBox("att", ViewBag.Attunement as int?, new { type = "number", min = "0", style = "width:50px;" })</div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">Endurance</div><div class="col-sm-5">@Html.TextBox("end", ViewBag.Endurance as int?, new { type = "number", min = "0", style = "width:50px;" })</div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">Vitality</div><div class="col-sm-5">@Html.TextBox("vit", ViewBag.Vitality as int?, new { type = "number", min = "0", style = "width:50px;" })</div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group row">
                        <div class="col-sm-6">Strength</div><div class="col-sm-5">@Html.TextBox("str", ViewBag.STR as int?, new { type = "number", min = "0", style = "width:50px;" })</div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">Dexterity</div><div class="col-sm-5">@Html.TextBox("dex", ViewBag.DEX as int?, new { type = "number", min = "0", style = "width:50px;" })</div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">Intelligence</div><div class="col-sm-5">@Html.TextBox("int", ViewBag.INT as int?, new { type = "number", min = "0", style = "width:50px;" })</div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">Faith</div><div class="col-sm-5">@Html.TextBox("fth", ViewBag.FTH as int?, new { type = "number", min = "0", style = "width:50px;" })</div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">Luck</div><div class="col-sm-5">@Html.TextBox("lck", ViewBag.Luck as int?, new { type = "number", min = "0", style = "width:50px;" })</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">Weapons <span style="float:right;">@Html.ActionLink("Weapon Search", "Index", "Weapons")</span></div>
            <div class="panel-body">
                <div class="form-group row">
                    <label class="col-sm-12">Right Weapon 1:</label>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2">@Html.DropDownList("rWeapon1Infusion", ViewBag.InfusionTypes as IEnumerable<SelectListItem>)</div>
                    <div class="col-sm-6">@Html.DropDownList("rWeapon1", ViewBag.Weapons as IEnumerable<SelectListItem>)</div>
                    <div class="col-sm-4">@Html.DropDownList("rWeapon1Upgrade", ViewBag.ReinforcementLevels as IEnumerable<SelectListItem>)</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12">Right Weapon 2:</label>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2">@Html.DropDownList("rWeapon2Infusion", ViewBag.InfusionTypes as IEnumerable<SelectListItem>)</div>
                    <div class="col-sm-6">@Html.DropDownList("rWeapon2", ViewBag.Weapons as IEnumerable<SelectListItem>)</div>
                    <div class="col-sm-4">@Html.DropDownList("rWeapon2Upgrade", ViewBag.ReinforcementLevels as IEnumerable<SelectListItem>)</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12">Right Weapon 3:</label>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2">@Html.DropDownList("rWeapon3Infusion", ViewBag.InfusionTypes as IEnumerable<SelectListItem>)</div>
                    <div class="col-sm-6">@Html.DropDownList("rWeapon3", ViewBag.Weapons as IEnumerable<SelectListItem>)</div>
                    <div class="col-sm-4">@Html.DropDownList("rWeapon3Upgrade", ViewBag.ReinforcementLevels as IEnumerable<SelectListItem>)</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12">Left Weapon 1:</label>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2">@Html.DropDownList("lWeapon1Infusion", ViewBag.InfusionTypes as IEnumerable<SelectListItem>)</div>
                    <div class="col-sm-6">@Html.DropDownList("lWeapon1", ViewBag.Weapons as IEnumerable<SelectListItem>)</div>
                    <div class="col-sm-4">@Html.DropDownList("lWeapon1Upgrade", ViewBag.ReinforcementLevels as IEnumerable<SelectListItem>)</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12">Left Weapon 2:</label>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2">@Html.DropDownList("lWeapon2Infusion", ViewBag.InfusionTypes as IEnumerable<SelectListItem>)</div>
                    <div class="col-sm-6">@Html.DropDownList("lWeapon2", ViewBag.Weapons as IEnumerable<SelectListItem>)</div>
                    <div class="col-sm-4">@Html.DropDownList("lWeapon2Upgrade", ViewBag.ReinforcementLevels as IEnumerable<SelectListItem>)</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12">Left Weapon 3:</label>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2">@Html.DropDownList("lWeapon3Infusion", ViewBag.InfusionTypes as IEnumerable<SelectListItem>)</div>
                    <div class="col-sm-6">@Html.DropDownList("lWeapon3", ViewBag.Weapons as IEnumerable<SelectListItem>)</div>
                    <div class="col-sm-4">@Html.DropDownList("lWeapon3Upgrade", ViewBag.ReinforcementLevels as IEnumerable<SelectListItem>)</div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">Armor <span style="float:right;">@Html.ActionLink("Armor Search", "Index", "Armor")</span></div>
            <div class="panel-body">
                <div class="form-group row">
                    <label class="col-sm-3">Helm:</label>
                    <div class="col-sm-7">@Html.DropDownList("helm", ViewBag.Helms as IEnumerable<SelectListItem>)</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3">Chest:</label>
                    <div class="col-sm-7">@Html.DropDownList("chest", ViewBag.Chests as IEnumerable<SelectListItem>)</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3">Gauntlets:</label>
                    <div class="col-sm-7">@Html.DropDownList("guantlet", ViewBag.Gauntlets as IEnumerable<SelectListItem>)</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3">Leggings:</label>
                    <div class="col-sm-7">@Html.DropDownList("legging", ViewBag.Leggings as IEnumerable<SelectListItem>)</div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">Rings</div>
            <div class="panel-body">
                <div class="form-group row">
                    <label class="col-sm-3">Ring 1:</label>
                    <div class="col-sm-7">@Html.DropDownList("ring1", ViewBag.Rings as IEnumerable<SelectListItem>)</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3">Ring 2:</label>
                    <div class="col-sm-7">@Html.DropDownList("ring2", ViewBag.Rings as IEnumerable<SelectListItem>)</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3">Ring 3:</label>
                    <div class="col-sm-7">@Html.DropDownList("ring3", ViewBag.Rings as IEnumerable<SelectListItem>)</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3">Ring 4:</label>
                    <div class="col-sm-7">@Html.DropDownList("ring4", ViewBag.Rings as IEnumerable<SelectListItem>)</div>
                </div>
            </div>
        </div>
    </div>
</div>